name: Signal Downstream Integrations

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master, develop, main]

jobs:
  signal:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to Downstream Repos
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: ${{ github.repository_owner }}/deploy
          event-type: protocol_release
          client-payload: >
            {
              "protocol_branch": "${{ github.head_ref }}",
              "pr_number": "${{ github.event.number }}",
              "owner": "${{ github.repository_owner }}"
            }
      - name: Dispatch to FaaS
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: ${{ github.repository_owner }}/faas
          event-type: protocol_release
          client-payload: >
            {
              "protocol_branch": "${{ github.head_ref }}",
              "pr_number": "${{ github.event.number }}",
              "owner": "${{ github.repository_owner }}"
            }
